AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-trip

  Rest API to manage a Trips

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref TripTable
        ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/serverless-trap-1.0-SNAPSHOT.jar
      Handler: br.com.fiap.handlers.CreateTripsHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        CreateTrips:
          Type: Api
          Properties:
            Path: /trip
            Method: post
  GetTripByIdHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/serverless-trap-1.0-SNAPSHOT.jar
      Handler: br.com.fiap.handlers.GetTripByIdHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        GetTripById:
          Type: Api
          Properties:
            Path: /trip/{id}
            Method: get
  GetTripsByPeriodHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/serverless-trap-1.0-SNAPSHOT.jar
      Handler: br.com.fiap.handlers.GetTripsByPeriodHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        GetTripById:
          Type: Api
          Properties:
            Path: /trip/period/{start}/{end}
            Method: get

  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: dateTrip
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: dateTrip
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  CreateTripsHandlerFunction:
    Description: CreateTrips Lambda Function ARN
    Value:
      Fn::GetAtt:
        - CreateTripsHandlerFunction
        - Arn
  GetTripByIdHandlerFunction:
    Description: GetTripById Lambda Function ARN
    Value:
      Fn::GetAtt:
        - GetTripByIdHandlerFunction
        - Arn
